packages:
  - "app/*"
  - "pkg/*"
  - "template/*"
  - "!**/test/**"

# "re 'supports-color': https://stackoverflow.com/questions/76591038/module-not-found-esm-packages-supports-color-need-to-be-imported-use-import",
catalog:
  '@hanzo/auth': 2.5.3
  '@hanzo/ui': 4.1.3
  '@types/node': 20.14.15
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  lucide-react: 0.456.0
  react-hook-form: 7.51.4
  next: 14.2.16
  react: 18.3.1
  react-dom: 18.3.1
  supports-color: 8.1.1
  tailwindcss: 3.4.14
  typescript: 5.6.3
